# Generated by Django 3.0.6 on 2020-05-31 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ancket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100, verbose_name='Дата анкеты')),
            ],
            options={
                'verbose_name': 'анкета',
                'verbose_name_plural': 'анкеты',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('note', models.TextField()),
            ],
            options={
                'verbose_name': 'болезнь',
                'verbose_name_plural': 'болезни',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_card', models.IntegerField(verbose_name='Номер карты')),
                ('FIO', models.CharField(max_length=100, verbose_name='ФИО')),
                ('date_birth', models.CharField(max_length=100, verbose_name='Дата рождения')),
                ('sex', models.CharField(max_length=50, verbose_name='Пол')),
                ('nationality', models.CharField(max_length=50, verbose_name='Национальность')),
                ('education', models.CharField(max_length=100, verbose_name='Образование')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('job', models.CharField(max_length=100, verbose_name='Место работы')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'пациента',
                'verbose_name_plural': 'пациенты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200, verbose_name='Логин')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('isAdmin', models.BooleanField(verbose_name='Я администратор')),
                ('FIO', models.CharField(default='', max_length=50, verbose_name='ФИО')),
                ('Postion', models.CharField(default='', max_length=50, verbose_name='Позиция')),
                ('Department', models.CharField(default='', max_length=50, verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'пользователя',
                'verbose_name_plural': 'пользователи',
            },
        ),
        migrations.CreateModel(
            name='Epicriz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invalid', models.BooleanField(default=False)),
                ('lechenie', models.CharField(default='', max_length=500, null=True, verbose_name='Лечение')),
                ('date_gospit', models.DateField(default='1999-01-01', null=True)),
                ('date_vipisky', models.DateField(default='1999-01-01', null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
            options={
                'verbose_name': 'эпикриз',
                'verbose_name_plural': 'эпикризы',
            },
        ),
        migrations.CreateModel(
            name='Diagnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disease')),
                ('epicriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Epicriz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
            options={
                'verbose_name': 'диагноз',
                'verbose_name_plural': 'диагнозы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField()),
                ('conviction', models.IntegerField(default=0)),
                ('ancket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ancket')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Question')),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'ответы',
            },
        ),
        migrations.AddField(
            model_name='ancket',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient', verbose_name='Пациент'),
        ),
    ]
