# Generated by Django 3.0.6 on 2020-05-31 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnos',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Disease'),
        ),
        migrations.AlterField(
            model_name='diagnos',
            name='epicriz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Epicriz'),
        ),
    ]
