# Generated by Django 3.0.6 on 2020-05-31 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200531_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnos',
            name='epicriz',
        ),
    ]
