# Generated by Django 3.0.6 on 2020-05-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200529_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='conviction',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=100, verbose_name='Вопрос'),
        ),
    ]
