# Generated by Django 3.0.6 on 2020-05-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200529_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Department',
            field=models.CharField(default='', max_length=50, verbose_name='Отделение'),
        ),
        migrations.AddField(
            model_name='user',
            name='FIO',
            field=models.CharField(default='', max_length=50, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='user',
            name='Postion',
            field=models.CharField(default='', max_length=50, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=200, verbose_name='Логин'),
        ),
    ]
