# Generated by Django 3.0.6 on 2020-05-31 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_diagnos_epicriz'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnos',
            name='epicriz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Epicriz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnos',
            name='disease',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Disease'),
            preserve_default=False,
        ),
    ]
